### ISSUE TITLE
jvm.args should also support arrays

### ISSUE THREAD

**Issue by mark-distrokid** [Ortus-Solutions/vscode-commandbox#26] opened 2022-08-05 09:42 UTC
As per https://commandbox.ortusbooks.com/embedded-server/configuring-your-server/jvm-args
the server validation gives an error if we use an array in VSCode in server.json

It should support string and array

**Comment by KamasamaK** [comment] 2022-08-05 09:45
Duplicate of #25

**Closed by KamasamaK** 2022-08-05 09:45 UTC
